# Generated by Django 4.2.22 on 2025-06-10 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du template')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('content', models.TextField(verbose_name='Contenu du template avec placeholders')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_public', models.BooleanField(default=False, verbose_name='Template public')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur (hex)')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Nom du champ')),
                ('field_label', models.CharField(max_length=200, verbose_name='Label affiché')),
                ('field_type', models.CharField(choices=[('text', 'Texte simple'), ('textarea', 'Texte long'), ('number', 'Nombre'), ('date', 'Date'), ('email', 'Email'), ('url', 'URL'), ('select', 'Liste déroulante')], default='text', max_length=20)),
                ('placeholder_text', models.CharField(blank=True, max_length=200, verbose_name="Texte d'aide")),
                ('is_required', models.BooleanField(default=False, verbose_name='Champ obligatoire')),
                ('field_options', models.TextField(blank=True, null=True, verbose_name='Options (pour select)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templates_app.template')),
            ],
            options={
                'verbose_name': 'Champ de template',
                'verbose_name_plural': 'Champs de template',
                'ordering': ['order', 'id'],
                'unique_together': {('template', 'field_name')},
            },
        ),
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_app.templatecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Document terminé')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='templates_app.template')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Valeur du champ')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='templates_app.document')),
                ('template_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates_app.templatefield')),
            ],
            options={
                'verbose_name': 'Valeur de champ',
                'verbose_name_plural': 'Valeurs de champs',
                'unique_together': {('document', 'template_field')},
            },
        ),
    ]
